#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom alakazam aminoAcidProperties
#' @importFrom alakazam getFamily
#' @importFrom ape Moran.I
#' @importFrom biomaRt getBM
#' @importFrom biomaRt listAttributes
#' @importFrom biomaRt listEnsemblArchives
#' @importFrom biomaRt listFilters
#' @importFrom biomaRt searchDatasets
#' @importFrom biomaRt useEnsembl
#' @importFrom clevr completeness
#' @importFrom clevr homogeneity
#' @importFrom cli cli_abort
#' @importFrom cli cli_inform
#' @importFrom cli cli_warn
#' @importFrom cluster silhouette
#' @importFrom clusterSim index.DB
#' @importFrom clValid dunn
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr count
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr group_modify
#' @importFrom dplyr join_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n_distinct
#' @importFrom dplyr na_if
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr slice_max
#' @importFrom dplyr slice_min
#' @importFrom dplyr summarize
#' @importFrom dplyr tally
#' @importFrom dplyr transmute
#' @importFrom dplyr ungroup
#' @importFrom dplyr vars
#' @importFrom DT datatable
#' @importFrom forcats fct_inseq
#' @importFrom forcats fct_relevel
#' @importFrom fpc cluster.stats
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 after_stat
#' @importFrom ggplot2 cut_interval
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 expansion
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_jitter
#' @importFrom ggplot2 geom_label
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_step
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 label_both
#' @importFrom ggplot2 label_wrap_gen
#' @importFrom ggplot2 labeller
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 position_dodge
#' @importFrom ggplot2 position_stack
#' @importFrom ggplot2 scale_color_gradientn
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_color_viridis_c
#' @importFrom ggplot2 scale_fill_gradientn
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 scale_y_discrete
#' @importFrom ggplot2 theme
#' @importFrom grDevices colorRampPalette
#' @importFrom knitr kable
#' @importFrom lsa cosine
#' @importFrom Matrix Matrix
#' @importFrom mclust adjustedRandIndex
#' @importFrom patchwork plot_layout
#' @importFrom patchwork wrap_plots
#' @importFrom purrr map_df
#' @importFrom purrr map_dfr
#' @importFrom purrr partial
#' @importFrom qs2 qd_read
#' @importFrom qs2 qd_save
#' @importFrom qs2 qs_read
#' @importFrom qs2 qs_save
#' @importFrom readr read_csv
#' @importFrom readr read_tsv
#' @importFrom recipes all_nominal_predictors
#' @importFrom recipes all_numeric_predictors
#' @importFrom recipes all_ordered_predictors
#' @importFrom recipes bake
#' @importFrom recipes prep
#' @importFrom recipes recipe
#' @importFrom recipes step_dummy
#' @importFrom recipes step_normalize
#' @importFrom recipes step_ordinalscore
#' @importFrom recipes step_unknown
#' @importFrom rlang sym
#' @importFrom scales breaks_pretty
#' @importFrom scales hue_pal
#' @importFrom scales label_comma
#' @importFrom scales label_percent
#' @importFrom Seurat AddMetaData
#' @importFrom Seurat Cells
#' @importFrom Seurat CellsByIdentities
#' @importFrom Seurat CreateAssayObject
#' @importFrom Seurat CreateDimReducObject
#' @importFrom Seurat CreateSeuratObject
#' @importFrom Seurat DefaultAssay
#' @importFrom Seurat DietSeurat
#' @importFrom Seurat DimPlot
#' @importFrom Seurat DotPlot
#' @importFrom Seurat FeaturePlot
#' @importFrom Seurat FindClusters
#' @importFrom Seurat FindMultiModalNeighbors
#' @importFrom Seurat FindNeighbors
#' @importFrom Seurat FindVariableFeatures
#' @importFrom Seurat GetAssayData
#' @importFrom Seurat Idents
#' @importFrom Seurat NoLegend
#' @importFrom Seurat NormalizeData
#' @importFrom Seurat RenameIdents
#' @importFrom Seurat RunPCA
#' @importFrom Seurat RunUMAP
#' @importFrom Seurat ScaleData
#' @importFrom Seurat UMAPPlot
#' @importFrom Seurat VariableFeatures
#' @importFrom Seurat VlnPlot
#' @importFrom Seurat WhichCells
#' @importFrom splatter minimiseSCE
#' @importFrom splatter newSplatParams
#' @importFrom splatter splatSimulate
#' @importFrom stats dist
#' @importFrom stats rexp
#' @importFrom stats runif
#' @importFrom stats setNames
#' @importFrom stringr str_c
#' @importFrom stringr str_pad
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_sort
#' @importFrom stringr str_split_1
#' @importFrom stringr str_subset
#' @importFrom tibble remove_rownames
#' @importFrom tibble tibble
#' @importFrom tidyr complete
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyr separate
#' @importFrom tidyr unite
#' @importFrom tidyselect all_of
#' @importFrom tidyselect everything
#' @importFrom tidyselect starts_with
#' @importFrom tidyselect where
#' @importFrom utils object.size
#' @importFrom utils setTxtProgressBar
#' @importFrom utils txtProgressBar
#' @importFrom xfun attr2
## usethis namespace: end
NULL
